
name: installation of testfile

on: push

jobs:
    test-jobs:
        runs-on: ubuntu-latest

        steps:
            - name: sample text "Hello"
              run: echo "Hello-NRS_DevOps"

            - name: create directory
              run: mkdir amma
            
            - name: switch directory to amma
              run: cd amma

            - name: create family file
              run: echo "Hello-NRS_DevOps" > /amma/annavadhina.txt